### ISSUE TITLE
Hello, thank you for your hard work. I am not a Kakao employee, I just like emoticons. The few sellers in China cannot update the new sales during the days when your tool cannot be downloaded. In some forums in China, they sell thousands of sets together. They arrogantly say that this tool is theirs. If you fix it, they also say that it is their own research and development. I feel that the fruits of your labor have been trampled by them, which violates your original intention. Is there any way to prevent Chinese people from using it? They only know your download, not the code.

### ISSUE THREAD

**Issue by luckyyaa** [laggykiller/sticker-convert#166] opened 2024-06-07 00:59 UTC

**Comment by laggykiller** [comment] 2024-06-07 01:29
Closing as duplicate of https://github.com/laggykiller/sticker-convert/issues/163

**Closed by laggykiller** 2024-06-07 01:29 UTC
