### ISSUE TITLE
In China, all shopping websites sell Kakao emoticons. They are all downloaded using your tools, which infringes on the rights of the authors. Although you are kind enough to let people download, unscrupulous people use it to make money. Please don't release the tool, or use it yourself and don't make it public.

### ISSUE THREAD

**Issue by luckyyaa** [laggykiller/sticker-convert#164] opened 2024-06-06 15:13 UTC

**Comment by laggykiller** [comment] 2024-06-06 15:15
Closing as duplicate of https://github.com/laggykiller/sticker-convert/issues/163

**Closed by laggykiller** 2024-06-06 15:15 UTC
