### ISSUE TITLE
You fixed the download, and someone immediately showed off, and he can make money

### ISSUE THREAD

**Issue by luckyyaa** [laggykiller/sticker-convert#165] opened 2024-06-06 23:28 UTC
![image](https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4/assets/164459050/bd50363a-2517-45c4-806e-131c232d5569)

**Comment by laggykiller** [comment] 2024-06-07 00:58
Closing as duplicate of https://github.com/laggykiller/sticker-convert/issues/163

**Closed by laggykiller** 2024-06-07 00:58 UTC
